import { ItemType } from '../interface';

export const laborLawItems: ItemType[] = [
  { tier: 'title', content: '目 录', value: 'catalogue' },
  { tier: 'content', content: '第一章 总则', value: 'catalogue-1' },
  { tier: 'content', content: '第二章 促进就业', value: 'catalogue-2' },
  { tier: 'content', content: '第三章 劳动合同和集体合同', value: 'catalogue-3' },
  { tier: 'content', content: '第四章 工作时间和休息休假', value: 'catalogue-4' },
  { tier: 'content', content: '第五章 工资', value: 'catalogue-5' },
  { tier: 'content', content: '第六章 劳动安全卫生', value: 'catalogue-6' },
  { tier: 'content', content: '第七章 女职工和未成年工特殊保护', value: 'catalogue-7' },
  { tier: 'content', content: '第八章 职业培训', value: 'catalogue-8' },
  { tier: 'content', content: '第九章 社会保险和福利', value: 'catalogue-9' },
  { tier: 'content', content: '第十章 劳动争议', value: 'catalogue-10' },
  { tier: 'content', content: '第十一章 监督检查', value: 'catalogue-11' },
  { tier: 'content', content: '第十二章 法律责任', value: 'catalogue-12' },
  { tier: 'content', content: '第十三章 附则', value: 'catalogue-13' },
  { tier: 'title', content: '第一章　总则', value: 'chapter-1' },
  { tier: 'content', content: '第一条　为了保护劳动者的合法权益，调整劳动关系，建立和维护适应社会主义市场经济的劳动制度，促进经济发展和社会进步，根据宪法，制定本法。', value: 'chapter1-1-1' },
  { tier: 'content', content: '第二条　在中华人民共和国境内的企业、个体经济组织（以下统称用人单位）和与之形成劳动关系的劳动者，适用本法。国家机关、事业组织、社会团体和与之建立劳动合同关系的劳动者，依照本法执行。', value: 'chapter1-2-1' },
  { tier: 'content', content: '第三条　劳动者享有平等就业和选择职业的权利、取得劳动报酬的权利、休息休假的权利、获得劳动安全卫生保护的权利、接受职业技能培训的权利、享受社会保险和福利的权利、提请劳动争议处理的权利以及法律规定的其他劳动权利。', value: 'chapter1-3-1' },
  { tier: 'content', content: '劳动者应当完成劳动任务，提高职业技能，执行劳动安全卫生规程，遵守劳动纪律和职业道德。', value: 'chapter1-3-2' },
  { tier: 'content', content: '第四条　用人单位应当依法建立和完善规章制度，保障劳动者享有劳动权利和履行劳动义务。', value: 'chapter1-4-1' },
  { tier: 'content', content: '第五条　国家采取各种措施，促进劳动就业，发展职业教育，制定劳动标准，调节社会收入，完善社会保险，协调劳动关系，逐步提高劳动者的生活水平。', value: 'chapter1-5-1' },
  { tier: 'content', content: '第六条　国家提倡劳动者参加社会义务劳动，开展劳动竞赛和合理化建议活动，鼓励和保护劳动者进行科学研究、技术革新和发明创造，表彰和奖励劳动模范和先进工作者。', value: 'chapter1-6-1' },
  { tier: 'content', content: '第七条　劳动者有权依法参加和组织工会。', value: 'chapter1-7-1' },
  { tier: 'content', content: '工会代表和维护劳动者的合法权益，依法独立自主地开展活动。', value: 'chapter1-7-2' },
  { tier: 'content', content: '第八条　劳动者依照法律规定，通过职工大会、职工代表大会或者其他形式，参与民主管理或者就保护劳动者合法权益与用人单位进行平等协商。', value: 'chapter1-8-1' },
  { tier: 'content', content: '第九条　国务院劳动行政部门主管全国劳动工作。', value: 'chapter1-9-1' },
  { tier: 'content', content: '县级以上地方人民政府劳动行政部门主管本行政区域内的劳动工作。', value: 'chapter1-9-2' },
  { tier: 'title', content: '第二章　促进就业', value: 'chapter-2' },
  { tier: 'content', content: '第十条　国家通过促进经济和社会发展，创造就业机会。', value: 'chapter2-10-1' },
  { tier: 'content', content: '国家鼓励企业、事业组织、社会团体在法律、行政法规规定的范围内兴办产业或者拓展经营，增加就业。', value: 'chapter2-10-2' },
  { tier: 'content', content: '国家支持劳动者自愿组织起来就业和从事个体经营实现就业。', value: 'chapter2-10-3' },
  { tier: 'content', content: '第十一条　地方各级人民政府应当采取措施，发展多种类型的职业介绍机构，提供就业服务。', value: 'chapter2-11-1' },
  { tier: 'content', content: '第十二条　劳动者就业，不因民族、种族、性别、宗教信仰不同而受歧视。', value: 'chapter2-12-1' },
  { tier: 'content', content: '第十三条　妇女享有与男子平等的就业权利。在录用职工时，除国家规定的不适合妇女的工种或者岗位外，不得以性别为由拒绝录用妇女或者提高对妇女的录用标准。', value: 'chapter2-13-1' },
  { tier: 'content', content: '第十四条　残疾人、少数民族人员、退出现役的军人的就业，法律、法规有特别规定的，从其规定。', value: 'chapter2-14-1' },
  { tier: 'content', content: '第十五条　禁止用人单位招用未满十六周岁的未成年人。', value: 'chapter2-15-1' },
  { tier: 'content', content: '文艺、体育和特种工艺单位招用未满十六周岁的未成年人，必须遵守国家有关规定，并保障其接受义务教育的权利。', value: 'chapter2-15-2' },
  { tier: 'title', content: '第三章　劳动合同和集体合同', value: 'chapter-3' },
  { tier: 'content', content: '第十六条　劳动合同是劳动者与用人单位确立劳动关系、明确双方权利和义务的协议。', value: 'chapter3-16-1' },
  { tier: 'content', content: '建立劳动关系应当订立劳动合同。', value: 'chapter3-16-2' },
  { tier: 'content', content: '第十七条　订立和变更劳动合同，应当遵循平等自愿、协商一致的原则，不得违反法律、行政法规的规定。', value: 'chapter3-17-1' },
  { tier: 'content', content: '劳动合同依法订立即具有法律约束力，当事人必须履行劳动合同规定的义务。', value: 'chapter3-17-2' },
  { tier: 'content', content: '第十八条　下列劳动合同无效：', value: 'chapter3-18-1' },
  { tier: 'content', content: '（一）违反法律、行政法规的劳动合同；', value: 'chapter3-18-2' },
  { tier: 'content', content: '（二）采取欺诈、威胁等手段订立的劳动合同。', value: 'chapter3-18-3' },
  { tier: 'content', content: '无效的劳动合同，从订立的时候起，就没有法律约束力。确认劳动合同部分无效的，如果不影响其余部分的效力，其余部分仍然有效。', value: 'chapter3-18-4' },
  { tier: 'content', content: '劳动合同的无效，由劳动争议仲裁委员会或者人民法院确认。', value: 'chapter3-18-5' },
  { tier: 'content', content: '第十九条　劳动合同应当以书面形式订立，并具备以下条款：', value: 'chapter3-19-1' },
  { tier: 'content', content: '（一）劳动合同期限；', value: 'chapter3-19-2' },
  { tier: 'content', content: '（二）工作内容；', value: 'chapter3-19-3' },
  { tier: 'content', content: '（三）劳动保护和劳动条件；', value: 'chapter3-19-4' },
  { tier: 'content', content: '（四）劳动报酬；', value: 'chapter3-19-5' },
  { tier: 'content', content: '（五）劳动纪律；', value: 'chapter3-19-6' },
  { tier: 'content', content: '（六）劳动合同终止的条件；', value: 'chapter3-19-7' },
  { tier: 'content', content: '（七）违反劳动合同的责任。', value: 'chapter3-19-8' },
  { tier: 'content', content: '劳动合同除前款规定的必备条款外，当事人可以协商约定其他内容。', value: 'chapter3-19-9' },
  { tier: 'content', content: '第二十条　劳动合同的期限分为有固定期限、无固定期限和以完成一定的工作为期限。', value: 'chapter3-20-1' },
  { tier: 'content', content: '劳动者在同一用人单位连续工作满十年以上，当事人双方同意续延劳动合同的，如果劳动者提出订立无固定期限的劳动合同，应当订立无固定期限的劳动合同。', value: 'chapter3-20-2' },
  { tier: 'content', content: '第二十一条　劳动合同可以约定试用期。试用期最长不得超过六个月。', value: 'chapter3-21-1' },
  { tier: 'content', content: '第二十二条　劳动合同当事人可以在劳动合同中约定保守用人单位商业秘密的有关事项。', value: 'chapter3-22-1' },
  { tier: 'content', content: '第二十三条　劳动合同期满或者当事人约定的劳动合同终止条件出现，劳动合同即行终止。', value: 'chapter3-23-1' },
  { tier: 'content', content: '第二十四条　经劳动合同当事人协商一致，劳动合同可以解除。', value: 'chapter3-24-1' },
  { tier: 'content', content: '第二十五条　劳动者有下列情形之一的，用人单位可以解除劳动合同：', value: 'chapter3-25-1' },
  { tier: 'content', content: '（一）在试用期间被证明不符合录用条件的；', value: 'chapter3-25-2' },
  { tier: 'content', content: '（二）严重违反劳动纪律或者用人单位规章制度的；', value: 'chapter3-25-3' },
  { tier: 'content', content: '（三）严重失职，营私舞弊，对用人单位利益造成重大损害的；', value: 'chapter3-25-4' },
  { tier: 'content', content: '（四）被依法追究刑事责任的。', value: 'chapter3-25-5' },
  { tier: 'content', content: '第二十六条　有下列情形之一的，用人单位可以解除劳动合同，但是应当提前三十日以书面形式通知劳动者本人：', value: 'chapter3-26-1' },
  { tier: 'content', content: '（一）劳动者患病或者非因工负伤，医疗期满后，不能从事原工作也不能从事由用人单位另行安排的工作的；', value: 'chapter3-26-2' },
  { tier: 'content', content: '（二）劳动者不能胜任工作，经过培训或者调整工作岗位，仍不能胜任工作的；', value: 'chapter3-26-3' },
  { tier: 'content', content: '（三）劳动合同订立时所依据的客观情况发生重大变化，致使原劳动合同无法履行，经当事人协商不能就变更劳动合同达成协议的。', value: 'chapter3-26-4' },
  { tier: 'content', content: '第二十七条　用人单位濒临破产进行法定整顿期间或者生产经营状况发生严重困难，确需裁减人员的，应当提前三十日向工会或者全体职工说明情况，听取工会或者职工的意见，经向劳动行政部门报告后，可以裁减人员。', value: 'chapter3-27-1' },
  { tier: 'content', content: '用人单位依据本条规定裁减人员，在六个月内录用人员的，应当优先录用被裁减的人员。', value: 'chapter3-27-2' },
  { tier: 'content', content: '第二十八条　用人单位违反本法第二十六条、第二十七条的规定解除劳动合同的，应当依照国家有关规定给予经济补偿。', value: 'chapter3-28-1' },
  { tier: 'content', content: '第二十九条　劳动者有下列情形之一的，用人单位不得依据本法第二十六条、第二十七条的规定解除劳动合同：', value: 'chapter3-29-1' },
  { tier: 'content', content: '（一）患职业病或者因工负伤并被确认丧失或者部分丧失劳动能力的；', value: 'chapter3-29-2' },
  { tier: 'content', content: '（二）患病或者负伤，在规定的医疗期内的；', value: 'chapter3-29-3' },
  { tier: 'content', content: '（三）女职工在孕期、产期、哺乳期内的；', value: 'chapter3-29-4' },
  { tier: 'content', content: '（四）法律、行政法规规定的其他情形。', value: 'chapter3-29-5' },
  { tier: 'content', content: '第三十条　用人单位解除劳动合同，工会认为不适当的，有权提出意见。如果用人单位违反法律、法规或者劳动合同，工会有权要求重新处理；劳动者申请仲裁或者提起诉讼的，工会应当依法给予支持和帮助。', value: 'chapter3-30-1' },
  { tier: 'content', content: '第三十一条　劳动者解除劳动合同，应当提前三十日以书面形式通知用人单位。', value: 'chapter3-31-1' },
  { tier: 'content', content: '第三十二条　有下列情形之一的，劳动者可以随时通知用人单位解除劳动合同：', value: 'chapter3-32-1' },
  { tier: 'content', content: '（一）在试用期内的；', value: 'chapter3-32-2' },
  { tier: 'content', content: '（二）用人单位以暴力、威胁或者非法限制人身自由的手段强迫劳动的；', value: 'chapter3-32-3' },
  { tier: 'content', content: '（三）用人单位未按照劳动合同约定支付劳动报酬或者提供劳动条件的。', value: 'chapter3-32-4' },
  { tier: 'content', content: '第三十三条　企业职工一方与企业可以就劳动报酬、工作时间、休息休假、劳动安全卫生、保险福利等事项，签订集体合同。集体合同草案应当提交职工代表大会或者全体职工讨论通过。', value: 'chapter3-33-1'  },
  { tier: 'content', content: '集体合同由工会代表职工与企业签订；没有建立工会的企业，由职工推举的代表与企业签订。', value: 'chapter3-33-2'},
  { tier: 'content', content: '第三十四条　集体合同签订后应当报送劳动行政部门；劳动行政部门自收到集体合同文本之日起十五日内未提出异议的，集体合同即行生效。', value: 'chapter3-34-1' },
  { tier: 'content', content: '第三十五条　依法签订的集体合同对企业和企业全体职工具有约束力。职工个人与企业订立的劳动合同中劳动条件和劳动报酬等标准不得低于集体合同的规定。', value: 'chapter3-35-1' },
]
